### ISSUE TITLE
Add CLI flag for already indexed database

### ISSUE THREAD

**Issue by Sanrrone** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#30]
Hi, it could be possible to don't give raw protein fasta? I'm thinking the use of a huge db (refseq for example), and index the db everytime you use it is a little a waste of time. could you add the option to give the program an indexed db?

regards

**Comment by jmtsuji** [comment]
@Sanrrone Interesting idea, thanks. We're currently overhauling the BackBLAST workflow in the `develop` branch and can potentially add this feature.

@LeeBergstrand What are your thoughts? Would be straightforward to add extra, optional flags for `--subject_proteome_db` and `--query_proteome_db`, for example.

**Comment by LeeBergstrand** [comment]
@Sanrrone The latest release version on MASTER branch is **designed to work with preformatted BLAST DB files** for both the subject and query. See our python code for running BLAST.

https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/blob/ee70ff9b8e1a7be55e828567280b22718bd3cb5d/BackBLAST.py#L55

See the use of the ```-db``` flag rather than the ```-subject``` flag.

@jmtsuji Dev. branch has been changed to use the ```-subject``` flag.

https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/blob/cdaddc47936d8cb21cde183bbadee2fe30381cbc/BackBLAST.py#L58

@Sanrrone If you want to use an newer version just swap out ```-subject``` flag for the ```-db``` as a temporary solution.

@jmtsuji It wouldn't be that hard to add a CLI flag as you mentioned above. Probably just one flag to swap between FASTA search mode and BLASTDB search mode.

**Comment by Sanrrone** [comment]
thanks you!
