### ISSUE TITLE
Error in rule generate_phylogenetic_tree

### ISSUE THREAD

**Issue by annabananakobana** [LeeBergstrand/BackBLAST_Reciprocal_BLAST#51]
Followed instructions from the "[develop](https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/tree/develop)" branch however ran into the following errors after running the last line of code from the recommended workflow. 

`BackBLAST run output_dir/config.yaml output_dir`

my code: `BackBLAST run rbb_pit/config.yaml rbb_pit`

![Screen Shot 2020-01-08 at 3 26 14 PM](https://user-images.githubusercontent.com/36188174/71945301-4e7cb680-322b-11ea-9ef7-8bae43b0ff56.png)

I just wanted the csv file, so I used "-t NA" in the setup code to bypass the phylogenetic tree. 

`BackBLAST setup -t NA query.faa query_genome.faa subject_dir output_dir`

my code: `BackBLAST setup -t NA mm_queryproteinlist.faa mmproteinrefseq.faa subject_dir rbb_pit`

Now having dramas with the heatmap...
![Screen Shot 2020-01-08 at 3 51 33 PM](https://user-images.githubusercontent.com/36188174/71946484-e039f300-322e-11ea-80ce-0059894cef8d.png)

**iqtree** potential cause, any thoughts?

**Comment by jmtsuji** [comment]
Hello @annabananakobana ,

Thanks for testing out the develop branch.

Indeed, it looks like GToTree might have run into an error. Could you please send me the log file for GToTree? Should be in `logging/logs/phylogeny/gtotree.log` in your output folder.

The error with the heatmap plotter looks different. It looks like you are missing the `genome_metadata.tsv` file. This file should have been generated by `BackBLAST setup`. Can you confirm whether `genome_metadata.tsv` exists?

If you want to be confident that BackBLAST has installed correctly on your system, you can run the rough test code for BackBLAST. From inside the repo folder, run:
```
mkdir -p testing/outputs
./BackBLAST run testing/inputs/config.yaml testing/outputs --notemp
```
See if it finishes without errors. Also check whether the reciprocal BLAST table from the test looks normal:

```
cmp testing/outputs_expected/blast/combine_blast_tables/blast_tables_combined.csv testing/outputs/blast/combine_blast_tables/blast_tables_combined.csv
# Will give no output if everything is okay
```

**Comment by annabananakobana** [comment]
Hello @jmtsuji, 

Thanks for your response! 


Here is the log file for GToTree: 
[gtotree.log](https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/files/4037405/gtotree.log)

 A bit confused by `ERROR: Alignment must have at least 3 sequences`. My query list has 16 and at least 11 of these were observed in the csv file to have successfully aligned when I bypassed this phylogenetic tree code.

I cannot seem to locate the `iqtree_out.treefile` as mentioned in: 
> cp: cannot stat ‘phylogeny/gtotree/iqtree_out/iqtree_out.treefile’: No such file or directory

The only file in the `iqtree_out` directory is `iqtree_out.log` that shows: 
![Screen Shot 2020-01-09 at 10 59 40 AM](https://user-images.githubusercontent.com/36188174/72019781-2e063800-32cf-11ea-8758-3e793f1d664c.png)

I can confirm that the `genome_metadata.tsv` file exists in my output directory.
There were also no problems with the test code following installation. 

Could this be an error in the formatting of my query gene file?
Thanks for your help!

**Comment by jmtsuji** [comment]
Hello @annabananakobana ,

Thanks for the log file and for running the test code. Great to know that the test is working.

Based on the GToTree log file, it looks like GToTree only ran on one genome for some reason. IQ-TREE failed because it needs a larger number of sequences to build a tree (so the `iqtree_out.treefile` file was never created).

A few questions based on this:

- In your `subject_dir`, you should have one file per genome, and each file should contain the entire predicted gene set (represented as amino acid sequences) for each genome. For example, if you want to test 3 subject genomes (organisms A, B, and C), you should have three files called `A.faa`, `B.faa`, and `C.faa` in the `subject_dir` folder. Is this the format you are using? It looks like GToTree only detected one input genome for some reason. It also looks like GToTree consistently found multiple copies of the ribosomal protein marker genes in the genome, which makes me wonder if maybe multiple genomes have been added to the same file.
- Would you mind sending your `config.yaml` file? This should help with debugging further.

Let's start with this debugging, and then we can look at `genome_metadata.tsv` after.

**Comment by annabananakobana** [comment]
Hello @jmtsuji, 
Thanks for that. I was assuming the `ERROR: Alignment must have at least 3 sequences` was referring to the number of query genes. Have rerun the analysis with 5 genomes (different species within the same Class) in the .faa format. I do have 1 genome in the .pep format - guessing I have to convert this?
However, this was again unsuccessful and failed on the same error:
[gtotree.log](https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/files/4055974/gtotree.log)
Here is the associated .yaml file: 
[config.txt](https://github.com/LeeBergstrand/BackBLAST_Reciprocal_BLAST/files/4056020/config.txt)
Thanks,
Anna

**Comment by jmtsuji** [comment]
Hello @annabananakobana ,

Thanks for sending these updated logs. At the bottom of the GToTree log, it mentions that only 2/5 of the input genomes passed its quality threshold required to build a whole genome tree:

```
#################################################################################
####                                 Done!!                                  ####
#################################################################################

  Overall, 2 genomes of the input 5 were retained (see notes below).

    Tree written to:
        phylogeny/gtotree/phylogeny/gtotree.tre

mv: cannot stat ‘phylogeny/gtotree/Aligned_SCGs.tre’: No such file or directory
    Alignment written to:
        phylogeny/gtotree/Aligned_SCGs.faa

    Summary file with comp./redund. estimates written to:
        phylogeny/gtotree/Genomes_summary_info.tsv

    Summary table with hits per target gene per genome written to:
        phylogeny/gtotree/SCG_hit_counts.tsv

    Partitions (for downstream use with mixed-model treeing) written to:
        phylogeny/gtotree/run_files/Partitions.txt

________________________________________________________________________________

  Notes:

    3 genome(s) removed due to having too few hits to the targeted SCGs.
    8 gene(s) had no hits in any genome.
    5 genome(s) had an estimated redundancy of >= 10%.

        Reported in "phylogeny/gtotree/run_files/".
________________________________________________________________________________
```

In general, it looks like GToTree is finding multiple copies of the single copy genes (SCGs) in most of your genomes and is filtering the genomes out from further analysis.

From looking at the genome names: are you trying to run eukaryotic genomes through BackBLAST (e.g., hamster)? If so, this would explain the issue -- GToTree is only designed to work with prokaryotes (bacteria and archaea). Maybe you are getting multiple hits because the genomes are diploid, for example? If you need a phylogeny for eukaryotic genomes, you'll have to generate it outside of BackBLAST and then supply it to BackBLAST manually.

Also, I noticed that your `query_genome_orfs` had `refseq` in the name. Are you using a genome as the reference, or the entire RefSeq database? For reciprocal BLAST to be effective, the `query_genome_orfs` should be predicted proteins of the source genome that the query sequences in the `query_genes` file came from.

The rest of the pipeline should still work, although we built this tool mainly thinking about prokaryotic genomes.

**Comment by annabananakobana** [comment]
Hello @jmtsuji,
Yes, I am processing eukaryotic genomes so that's good to know that the pipeline is optimised for prokaryotes. Are the results in the csv output file still expected to be reliable? Or are you aware of any other programmes that might be more compatible with eukaryotic data? Some of my query sequences that are expected to have aligned are missing from the output so I am wondering if I should double check with another pipeline? I lowered the e-value threshold to 1e-10 without any change to output. 
No, the `refseq` in the name was referring to the fact that it is the protein seq, sorry if that was misleading.

**Comment by jmtsuji** [comment]
Hello @annabananakobana ,

Good to know that you are working with eukaryotes. Do you know if the reference genome sequence you are working with (i.e., `query_genome_orfs`) contains only a haploid version of the genome or both copies of all genes? If it contains copies of both genes (i.e., both alleles), this will interfere with reciprocal BLAST because the reverse BLAST search might hit the second copy of the gene instead of the query sequence, and this would incorrectly register as a negative result. BackBLAST should work if your reference genome sequence is haploid.

> No, the refseq in the name was referring to the fact that it is the protein seq, sorry if that was misleading.

Okay, good to know that you're using a genome sequence as the reference.

> Or are you aware of any other programmes that might be more compatible with eukaryotic data?

If your main goal is to detect certain gene homologs/orthologs in your genomes, then you have a lot of different tool options available to you. You could use OrthoMCL to detect a large number of genes in your genomes, for example. Or if you're only looking for a few targeted genes, you could even run regular BLASTP or hmmsearch on your samples using an appropriate query and then verify that the genes you detected are likely the right genes (e.g., by confirming that they have certain functional sites). This requires more manual effort, however. In theory, BackBLAST should be compatible with eukaryotic data as long as the query reference sequence is haploid (see comment above).

As a final note, having lots of closely-related paralogs in your reference genome can also cause problems with the reciprocal BLAST approach. For example, if your query's reference genome has 3 nearly identical copies of the same gene for some reason, it will cause the reverse BLAST search to incorrectly fail sometimes, like what I mentioned above for if you have a diploid genome. Does this make sense?

**Comment by annabananakobana** [comment]
Hello @jmtsuji, 
The assembly type of my query genome is haploid with alternative loci, which means it is likely interfering with the reverse blast as you detail above. 
Thanks for explaining the programmes, I will investigate further with a manual blast and go from there. 
Thank you for your help!

**Comment by jmtsuji** [comment]
Hello @annabananakobana ,

Ah, so maybe the alternative loci are causing the issue. In this case, it might be wise to manually examine BLASTP results as you mentioned (or to use a query reference genome with all alternative loci stripped out).

All the best with your analysis!
